image:
  mvn_npm:latest

#cache:
#  paths:
#    - .m2/repository/

stages:
  - build
  - analysis

maven:
#  variables:
#      CI_DEBUG_TRACE: "true"
  stage: build
  artifacts:
    untracked: true
  script:
  - mvn --batch-mode clean test


#https://github.com/gabrie-allaigre/sonar-gitlab-plugin
sonarqube-preview:
  stage: analysis
  variables:
    CI_DEBUG_TRACE: "true"
    SONAR_URL: "http://sonarqube:9000"
  script:
    - git checkout origin/master
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_EMAIL
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.all_issues=false -Dsonar.gitlab.only_issue_from_commit_line=true -Dsonar.gitlab.comment_no_issue=true


sonarqube-reports-master:
  stage: analysis
  only:
    - master

  variables:
#      CI_DEBUG_TRACE: "true"
      SONAR_URL: "http://sonarqube:9000"

  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.gitlab.project_id=$CI_PROJECT_PATH




sonarqube-reports-merge-request:
  variables:
#      CI_DEBUG_TRACE: "true"
      SONAR_URL: "http://sonarqube:9000"
      SONAR_PROJECT_NAME: java-code-doctor-sample--$CI_COMMIT_REF_NAME
  script:
    - git checkout origin/master
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_EMAIL
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=publish -Dsonar.projectKey=$SONAR_PROJECT_NAME -Dsonar.projectName=$SONAR_PROJECT_NAME
  stage: analysis
  except:
    - develop
    - master
    - /^hotfix_.*$/
    - /.*-hotfix$/




################
#  only:
#    - master

#  tags:
#    - java


#stages:
#- analysis
#
#sonarqube:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://localhost:9000"
#    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
#    SONAR_ANALYSIS_MODE: "issues"
#  script:
#  - /usr/bin/sonar-scanner-run.sh
#
#sonarqube-reports:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://localhost:9000"
#    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
#    SONAR_ANALYSIS_MODE: "publish"
#  script:
#  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh


# trigger build2


#check-ws:
#  stage: analysis
#  script:
#  - ls -l

#sonarqube:
#  variables:
#      CI_DEBUG_TRACE: "true"
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://sonarqube:9000"
#    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
#    SONAR_ANALYSIS_MODE: "issues"
#  script:
#  - /usr/bin/sonar-scanner-run.sh
#
#sonarqube-reports:
#  variables:
#      CI_DEBUG_TRACE: "true"
#  stage: test
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://sonarqube:9000"
#    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
#    SONAR_ANALYSIS_MODE: "publish"
#  script:
#  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh
#  only:
#  - master

