image:
  maven:latest

#cache:
#  paths:
#    - .m2/repository/

stages:
  - build
  - analysis

maven:
  variables:
      CI_DEBUG_TRACE: "true"
  stage: build
  artifacts:
    untracked: true
  script:
  - ls -l
  - mvn clean test
  - ls -l

#check-ws:
#  stage: analysis
#  script:
#  - ls -l

sonarqube:
  variables:
      CI_DEBUG_TRACE: "true"
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "http://sonarqube:9000"
    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
    SONAR_ANALYSIS_MODE: "issues"
  script:
  - /usr/bin/sonar-scanner-run.sh

sonarqube-reports:
  variables:
      CI_DEBUG_TRACE: "true"
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "http://sonarqube:9000"
    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
    SONAR_ANALYSIS_MODE: "publish"
  script:
  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh



#stages:
#- analysis
#
#sonarqube:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://localhost:9000"
#    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
#    SONAR_ANALYSIS_MODE: "issues"
#  script:
#  - /usr/bin/sonar-scanner-run.sh
#
#sonarqube-reports:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://localhost:9000"
#    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
#    SONAR_ANALYSIS_MODE: "publish"
#  script:
#  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh


# trigger build2
