image:
  maven:latest

#cache:
#  paths:
#    - .m2/repository/

stages:
  - build
  - test
  - analysis

maven:
  variables:
      CI_DEBUG_TRACE: "true"
  stage: build
  artifacts:
    untracked: true
  script:
  - ls -l
  - mvn --batch-mode clean compile
  - ls -l

#check-ws:
#  stage: analysis
#  script:
#  - ls -l

#sonarqube:
#  variables:
#      CI_DEBUG_TRACE: "true"
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://sonarqube:9000"
#    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
#    SONAR_ANALYSIS_MODE: "issues"
#  script:
#  - /usr/bin/sonar-scanner-run.sh
#
#sonarqube-reports:
#  variables:
#      CI_DEBUG_TRACE: "true"
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://sonarqube:9000"
#    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
#    SONAR_ANALYSIS_MODE: "publish"
#  script:
#  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh


sonarqube_preview:
  script:
    - git checkout origin/master
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test
  except:
    - develop
    - master
    - /^hotfix_.*$/
    - /.*-hotfix$/
#  tags:
#    - java

sonarqube:
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL
  stage: test
  only:
    - master
#  tags:
#    - java


#stages:
#- analysis
#
#sonarqube:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://localhost:9000"
#    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
#    SONAR_ANALYSIS_MODE: "issues"
#  script:
#  - /usr/bin/sonar-scanner-run.sh
#
#sonarqube-reports:
#  stage: analysis
#  image: ciricihq/gitlab-sonar-scanner
#  variables:
#    SONAR_URL: "http://localhost:9000"
#    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
#    SONAR_ANALYSIS_MODE: "publish"
#  script:
#  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh


# trigger build2
